services:
  postgres:
    image: postgres:17

    container_name: novacart-postgres

    restart: unless-stopped

    environment:
      POSTGRES_USER: novacart
      POSTGRES_PASSWORD: novacart123
      POSTGRES_DB: novacart_db

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: